== OpenTracing Example

=== Introduction

This example shows how to use Camel with OpenTracing to trace all
incoming and outgoing Camel messages.

The example uses a ElastiCo APM Client.

Route client -> service1 using HTTP.

=== Before you start

You need to configure EAK stack - Elasticsearch, APM Server and Kibana
Please follow https://www.elastic.co/guide/en/apm/get-started/current/install-and-run.html to get up and running

=== Build

You will need to compile this example first:

[source,sh]
----
$ mvn compile
----

=== Run the example

[source,sh]
----
$ mvn compile spring-boot:run

The client application explicitly instantiates and initializes the
implementation

=== View results
After seeing in console messages from timer, visit Kibana to view traces -
http://localhost:5601/app/apm#/services/Service1Application/transactions/
select any transaction and click "View full trace"

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/support.html[let us know].

We also love contributors, so
https://camel.apache.org/contributing.html[get involved] :-)

The Camel riders!
