services:
  lra-coordinator:
    image: "quay.io/jbosstm/lra-coordinator:latest"
    network_mode: "host"
  amq-broker:
    image: "apache/artemis:latest-alpine"
    environment:
      - ARTEMIS_USER=admin
      - ARTEMIS_PASSWORD=admin
    ports:
      - "8161:8161"
      - "61616:61616"
