{
 "title": "Camel metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Count by component",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gr/s" } },
   "targets": [
    {
     "expr": "sum(rate(camel_component_seconds_count[1m])) by (component)",
     "legendFormat": "{{greeting_name}}"
    }
   ]
  },
  {
   "title": "Trigger",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "gr/s" } },
   "targets": [
    {
     "expr": "sum(rate(trigger_seconds_count[1m])) by (component)",
     "legendFormat": "{{greeting_name}}"
    }
   ]
  },
  {
   "title": "HTTP POST by component",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "gr/s" } },
   "targets": [
    {
     "expr": "sum(rate(POST_seconds_count[1m])) by (component)",
     "legendFormat": "{{greeting_name}}"
    }
   ]
  }
 ]
}