== Twitter Salesforce Example

=== Introduction

This example listen for tweets which are mentioning the `+@cameltweet+`
twitter account. Information from the user whom mentions is then created
as a contact in Salesforce.

=== Configuring Twitter

This example ships with the keys and tokens of a long-standing testing
Twitter/X account named `cameltweet`, used only to let the example show
a complete, working configuration; they are not a working credential you
can rely on. They predate Twitter/X's 2023 API overhaul and are very
likely no longer valid, and even if they were, they are for a shared
testing account, not something to build on.

You must self-provision your own Twitter/X developer app and use its
consumer key/secret and access token/secret in place of the values in
`+application.properties+` before this example will actually run.

=== Configuring Salesforce

This example ships with `+clientId+`/`+clientSecret+` values for a Camel
test Salesforce developer account, included only to show what a filled-in
configuration looks like. As with the Twitter/X keys above, self-provision
your own Salesforce Developer account at
https://developer.salesforce.com/ for anything beyond reading this
example, and follow the steps below to create your own Connected
Application for your integration.

To do this after logging in to your Salesforce Developer account,
navigate to _Apps_ located under _Build_ and then _Create_, there you
should see _Connected Apps_ table in the heading click on _New_ and fill
in the indicated required fields and enable the _OAuth Settings_, for
_Callback URL_ you can use
https://login.salesforce.com/services/oauth2/success.

In the _Available OAuth Scopes_ add _Access and manage your data (api)_
and _Perform requests on your behalf at any time (refresh_token,
offline_access)_.

After clicking _Save_ click on _Manage_ on the top of the page and then
click on _Edit Policies_. Change the _IP Relaxation_ to _Relax IP
restrictions_ and click on _Save_.

*NOTE:* This will get you started quicker, but production you should
re-evaluate to comply with your security needs.

Next gather your _Consumer Key_ (_clientId_ property), _Consumer Secret_
(clientSecret) and either use username and password of the developer
account; or get the refresh token from Salesforce (more on this below).

==== Adding the Twitter screen name custom field

The example adds a custom field to _Contact_ SObject, to add it to your
Salesforce environment go into _Customize_ under _Build_ and choose
_Fields_ under _Contact_.

In _Contact Custom Fields & Relationships_ click on _New_ and add a
field of type `+Text+` with field label `+Twitter Screen Name+`, length
of 15 and for uniqueness select _Do not allow duplicate values_ and set
the _Set this field as the unique record identifier from an external
system_.

==== Getting the OAuth refresh token

In your browser go to the URL change the `+__YOUR_CLIENT_ID_HERE__+`
with your connected application _Consumer Key_:

`+https://login.salesforce.com/services/oauth2/authorize?response_type=token&client_id=+`**YOUR_CLIENT_ID_HERE**`+&redirect_uri=https://login.salesforce.com/services/oauth2/success&display=touch+`

Allow access to the application, and you’ll end up on a page with
`+refresh_token+` after the `+#+`, something like:

`+https://login.salesforce.com/services/oauth2/success#access_token=..&refresh_token=+`**<refresh_token>**`+&instance_url=...&issued_at=...&signature=...&scope=...&token_type=Bearer+`

==== How to generate Salesforce Data Transfer Objects (DTOs)

The best way to generate Java representation of Salesforce SObjects is
to use the `+camel-salesforce-maven-plugin+` and specify the desired DTO in <configuration> section, for example:

....
        <configuration>
            <clientId>${camelSalesforce.clientId}</clientId>
            <clientSecret>${camelSalesforce.clientSecret}</clientSecret>
            <userName>${camelSalesforce.userName}</userName>
            <password>${camelSalesforce.password}</password>
            <includes>
                <include>Contact</include>
            </includes>
        </configuration>
....

To generate only DTOs needed for Contact, but the parameter value can be
specified using regular expressions.

Running that plugin needs a live login against a real org, so it only
runs under the `+generate-salesforce-dto+` profile (`+-Dgenerate.dto+`),
never during a plain `+mvn compile+`. Because of that, the route can't
statically reference the generated `+org.apache.camel.salesforce.dto.Contact+`
class - it may not exist on the classpath. Instead
`+TwitterSalesforceRoute+` looks it up by name via reflection, using it
when present (e.g. after running with `+-Dgenerate.dto+` against your
own org) and otherwise falling back to the minimal, hand-maintained
`+org.apache.camel.example.mention.dto.Contact+` bundled with the
example, which is enough to compile and run without any Salesforce
credentials at build time.

=== Build

You will need to compile this example first:

....
mvn compile
....

=== Run

To run the example type using _generate.dto_ profile

....
mvn -DcamelSalesforce.clientId=3<client id> \
    -DcamelSalesforce.clientSecret=<client secret> \
    -DcamelSalesforce.userName=<username> \
    -DcamelSalesforce.password=<password> -Dgenerate.dto spring-boot:run
....

To stop the example hit ctrl+c

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/community/support/[let us know].

We also love contributors, so
https://camel.apache.org/community/contributing/[get involved] :-)

The Camel riders!
