camel.main.name=QdrantRAGExample
camel.main.run-controller=true

input.dir=input

# Qdrant
camel.component.qdrant.host=localhost
camel.component.qdrant.port=6334
camel.component.qdrant.max-results=10

# OpenAI component (configured for Ollama)
camel.component.openai.base-url=http://localhost:11434/v1
camel.component.openai.api-key=ollama
camel.component.openai.model=granite4:3b
camel.component.openai.embedding-model=nomic-embed-text
