camel.main.name=MilvusCitiesExample
camel.main.run-controller=true

input.dir=input

# Milvus
camel.component.milvus.host=localhost
camel.component.milvus.port=19530

# OpenAI component (configured for Ollama)
camel.component.openai.base-url=http://localhost:11434/v1
camel.component.openai.api-key=ollama
camel.component.openai.model=granite4:3b
