== Camel with Spring Boot AOT

This example shows how you can build and execute a native image by leveraging Spring Boot AOT to launch
Camel routes written in Java, XML and YAML in native mode.

=== How to build

To be able to build a GraalVM Native Image, you need to have GraalVM installed on your local machine.

1. So first, download it from https://github.com/graalvm/graalvm-ce-builds/releases, choose Java 17 (or newer) and the archive corresponding to your platform. Recent GraalVM distributions (22.3+) bundle `native-image` out of the box, so there is no separate `gu install native-image` step to run.
2. Then, sets the environment variable `JAVA_HOME` to the home directory of GraalVM.

Once the 2 steps are done properly, you can build the application with the next command:

[source,console]
----
mvn -Pnative native:compile
----

Building a GraalVM Native Image is a relatively slow process, so be patient, it should take a couple of minutes.

=== How to run

A GraalVM Native Image is a complete, platform-specific executable. At this point, you don't need any Java Virtual
Machine to launch your application.

So just, launch the executable file created in the target directory as next:

[source,console]
----
./target/camel-example-spring-boot-aot-basic
----

Your application will start in native mode. The output of the application should be of the next type:

[source]
----
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v4.1.1)

2026-09-03T19:25:47.907+02:00  INFO 52866 --- [           main] sample.camel.Application                 : Starting AOT-processed Application using Java 25.0.4.1 with PID 52866 (xxx/camel-spring-boot-examples/aot-basic/target/camel-example-spring-boot-aot-basic started by yyy in xxx/camel-spring-boot-examples/aot-basic)
2026-09-03T19:25:47.907+02:00 DEBUG 52866 --- [           main] sample.camel.Application                 : Running with Spring Boot v4.1.1, Spring v7.0.9
2026-09-03T19:25:47.907+02:00  INFO 52866 --- [           main] sample.camel.Application                 : No active profile set, falling back to 1 default profile: "default"
2026-09-03T19:25:47.919+02:00 DEBUG 52866 --- [           main] o.a.c.i.h.DefaultHealthCheckRegistry     : HealthCheckRepository with id registry-health-check-repository successfully registered
2026-09-03T19:25:47.960+02:00  INFO 52866 --- [           main] o.a.c.impl.engine.AbstractCamelContext   : Apache Camel 4.23.0-SNAPSHOT (MyCamelNative) is starting
2026-09-03T19:25:47.961+02:00  INFO 52866 --- [           main] c.s.b.CamelSpringBootApplicationListener : Starting CamelMainRunController to ensure the main thread keeps running
2026-09-03T19:25:47.961+02:00  INFO 52866 --- [inRunController] org.apache.camel.main.MainSupport        : Apache Camel (Main) 4.23.0-SNAPSHOT is starting
2026-09-03T19:25:47.961+02:00  INFO 52866 --- [           main] o.a.c.impl.engine.AbstractCamelContext   : Routes startup (total:3)
2026-09-03T19:25:47.961+02:00  INFO 52866 --- [           main] o.a.c.impl.engine.AbstractCamelContext   :     Started helloJava (timer://java)
2026-09-03T19:25:47.961+02:00  INFO 52866 --- [           main] o.a.c.impl.engine.AbstractCamelContext   :     Started helloYAML (timer://yaml)
2026-09-03T19:25:47.961+02:00  INFO 52866 --- [           main] o.a.c.impl.engine.AbstractCamelContext   :     Started helloXML (timer://xml)
2026-09-03T19:25:47.961+02:00  INFO 52866 --- [           main] o.a.c.impl.engine.AbstractCamelContext   : Apache Camel 4.23.0-SNAPSHOT (MyCamelNative) started in 1ms (build:0ms init:0ms start:1ms)
2026-09-03T19:25:47.962+02:00  INFO 52866 --- [           main] sample.camel.Application                 : Started Application in 0.066 seconds (process running for 0.081)
2026-09-03T19:25:48.966+02:00  INFO 52866 --- [ - timer://java] helloJava                                : Hello World From Java I am invoked 1 times at Thu Sep 03 19:25:48 CEST 2026
2026-09-03T19:25:48.966+02:00  INFO 52866 --- [ - timer://yaml] helloYAML                                : Hello World from YAML at Thu Sep 03 19:25:48 CEST 2026
2026-09-03T19:25:48.966+02:00  INFO 52866 --- [3 - timer://xml] helloXML                                 : Hello World From XML at Thu Sep 03 19:25:48 CEST 2026
----

As you can see the application took only *66* milliseconds to fully start while the exact same application in JVM mode
starts in more than *1* second.

For more details, please check the related https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html[Spring Boot documentation].

=== Help and contributions

If you hit any problem using Camel or have some feedback, then please
https://camel.apache.org/support.html[let us know].

We also love contributors, so
https://camel.apache.org/contributing.html[get involved] :-)

The Camel riders!
