global:
    scrape_interval: 15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
          - targets: ['host.docker.internal:9090']
    - job_name: 'webservices'
      metrics_path: '/actuator/prometheus'
      static_configs:
          - targets: ['host.docker.internal:6543','host.docker.internal:7654','host.docker.internal:5432']
